       "oso de peluche",
       "reloj",
       "oro",
       "caca",
       "carbon",
       "waifu",
       "la novia de cesur",
       "la mama de santi",
       "masitas",
       "nada",
       "lentes",
       "boleto dorado a la fabrica",
       "vandal",
       "celular",
       "nariz michael jackson",
       "manos de peron",
       "ganas de vivir",
       "nft",
       "bitcoin",
       "mate",
       "droga",
       "las piernas de maradona",
       "rei chiquita",
       "una novia",
       "un abrazo",
       "descuento en penes de goma",
       "jamon crudo",
       "papas fritas",
       "Ricky Martin",
       "La Mona Jimenez",
       "el Scania de maradona",
       "el Bazo de Joaco",
       "a Chile del mundial",
       "el paquete de cigarrillos que fue a buscar tu papa",
       "un saludo de Merlu",
       "un insulto de Merlu",
       "un ventilador liliana",
       "un cafecito de Moni Argento",
       "una gorreada",
       "la locura impredecible de Jinx",
       "a Batman",
       "muñeco inflable de Henry Cavill",
       "cabeza de Exodia",
       "brazo derecho de Exodia",
       "brazo izquierdo de Exodia",
       "pierna derecha de Exodia",
       "pierna izquierda de Exodia",
       "dragon de ojos azules",
       "la esfera del dragon 1",
       "la esfera del dragon 2",
       "la esfera del dragon 3",
       "la esfera del dragon 4",
       "la esfera del dragon 5",
       "la esfera del dragon 6",
       "la esfera del dragon 7",
       "las Islas Malvinas",
       "la tortuga de Buscando a Nemo",
       "a Calamardo",
       "una pata de palo",
       "1kg de helado de Cesur",
       "un depto en New York",
       "un depto en Once",
       "un Martin Fierro",
       "una pata de conejo",
       "un conejo sin una pata",
       "a Pepinillo Rick",
       "un alfajor de Malphite",
       "un Dementor",
       "un Demogorgon",
       "a Charmander",
       "a Bulbasaur",
       "a Squirtle",
       "la Copa del Mundial",
       "un gorrito de Eve",
       "un insulto de Eve",
       "un insulto de Cesur",
       "un timeout de 60s",
       "una loli",
       "una estrella para Boca",
       "un vino en carton",
       "una cumbiancha",
       "25g de merca",
       "un porrito", 
       "un mouse gaming",
       "un teclado mecanico",
       "un ban por 15 minutos",
       "una trompada",
       "un bife con papas",
       "el amor de tus padres",
       "una foto teta",
       "una nude",
       "una lofi girl estudiosa",
       "un objeto que no era pastel",
       "un pastel que no era objeto",
       "una referencia de Jojo",
       "una pc gamer",
       "una bolinet",
       "la tercera ☆☆☆",
       "una pala",
       "un follow en Instagram",
       "un follow en Twitter",
       "un follow en Twitch",
       "un gato",
       "un perro",
       "un game de lol conmigo",
       "un game de valorant conmigo",
       "un game de cs conmigo",
       "un game del juego que quieras conmigo",
       "un sombrero vaquero",
       "una cita con bts",
       "una rtx 4090",
       "una billetera vacia",
       "una billetera con plata",
       "una latita de coca",
       "1 dolar",
       "una enfermedad terminal",
       "la cura de una enfermedad terminal",
       "a Messi Chiquito",
       "una Pizza con Piña",
       "una Empanada de Carne Con Pasas",
       "la Empanada de tu Vieja",
       "el Choripan de tu Viejo",
       "un Sugar Daddy",
       "una Sugar Mommy",
       "un Beso",
       'la Patagonia',
       'una Coca Cola',
       'un Ibuprofeno',
       'el cadaver de la novia',
       'un partido de fubol',
       'a Messi Chiquito',
       'un ticket para ver un video',
       'un ticker para ver una peli',
       'un viaje a Europa',
       'un viaje a Africa',
       'un viaje a Japon',
       'un viaje a la concha de tu heraman',
       'un raid',
       'un insulto gratis a Merlu',
       'un puchito con coquita',
       'un barquito',
       'un bombardeo gratis',
       'el Monumental',
       'la Bombonera',
       'el Cilindro de Avellaneda',
       'el Libertadores de America',
       'un golpe militar',
       'un ticket para agregar un item a la maquinita',
       'un ticket para chuparme un huevo',
       'GTA 6',
       'a Elon Musk',
       'el pajarito de Twitter',
       'a Javier Milei',
       'a Ricardo Fort',
       'a Luis Miguel',
       'un evento canonico',
       'un evento no canonico',
       'un ticket para mostrar tu talento',
       'un ticket para contarme un chiste',
       );
   $random = array_rand($respuestas);
   echo $respuestas[$random];
?>